FROM java:8
WORKDIR /
ADD server/target/fat.jar Server.jar
ADD https://repository.sonatype.org/service/local/artifact/maven/content?r=central-proxy&g=mysql&a=mysql-connector-java&e=jar&v=LATEST mysql-driver.jar
EXPOSE 8080
CMD java -cp *.jar
